version: '2'
services:
    weblatex:
        restart: unless-stopped
        build: .
        image: dtek/sharelatex:latest
        depends_on:
            - weblatex-mongo
            - weblatex-redis
        ports:
            - 14738:80
        links:
            - weblatex-mongo
            - weblatex-redis
        volumes:
            - ../sharelatex_data:/var/lib/sharelatex
            - /var/run/docker.sock:/var/run/docker.sock
            #- /var/clsi/compiles:/var/www/sharelatex/clsi/compiles
        environment:
            SHARELATEX_MONGO_URL: mongodb://weblatex-mongo/weblatex
            SHARELATEX_REDIS_HOST: weblatex-redis
            SHARELATEX_APP_NAME: dTeX
            SHARELATEX_TEMPLATES_USER_ID: 5be99bf47dfd8700840f09ca
            SHARELATEX_NEW_PROJECT_TEMPLATE_LINKS: '[ {"name":"Rapportmall","url":"/read/mkhxkwscqnvf"} ]'

            SHARELATEX_SITE_URL: https://dtex.dtek.se
            SHARELATEX_NAV_TITLE: dTeX
            SHARELATEX_HEADER_IMAGE_URL: https://dtek.se/datalogo.svg
            SHARELATEX_ADMIN_EMAIL: dhack@dtek.se

            SHARELATEX_LEFT_FOOTER: '[{"text": "Hacke typs&auml;tter snabbare"} ]'
            SHARELATEX_RIGHT_FOOTER: '[{"text": "aspa sekreterare! ;)"} ]'

    weblatex-mongo:
        restart: always
        image: mongo:latest
        expose:
            - 27017
        volumes:
            - ../mongo_data:/data/db

    weblatex-redis:
        restart: always
        image: redis:latest
        expose:
            - 6379
        volumes:
            - ../redis_data:/data
